error_page 400 /error-pages/400.html;
error_page 401 /error-pages/401.html;
error_page 403 /error-pages/403.html;
error_page 404 /error-pages/404.html;
error_page 405 /error-pages/405.html;
error_page 408 /error-pages/408.html;
error_page 409 /error-pages/409.html;
error_page 410 /error-pages/410.html;
error_page 418 /error-pages/418.html;
error_page 422 /error-pages/422.html;
error_page 429 /error-pages/429.html;
error_page 451 /error-pages/451.html;
error_page 500 /error-pages/500.html;
error_page 501 /error-pages/501.html;
error_page 502 /error-pages/502.html;
error_page 503 /error-pages/503.html;
error_page 504 /error-pages/504.html;

location = /teapot {
    return 418;
}

location = /teapot/ {
    return 418;
}

location /error-pages/ {
    try_files $uri $uri/ /error-pages/404.html;
}
